name: CI
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '5.6'
            phpunit: '^5.7'
          - php-version: '7.0'
            phpunit: '^6.5'
          - php-version: '7.1'
            phpunit: '^7.5'
          - php-version: '7.2'
            phpunit: '^7.5'
          - php-version: '7.3'
            phpunit: '^7.5'
          - php-version: '7.4'
            phpunit: '^7.5'
          - php-version: '8.0'
            phpunit: '^9'
          - php-version: '8.1'
            phpunit: '^9'
    name: PHP ${{ matrix.php-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: redis

    - name: Setup Redis
      run: sudo add-apt-repository ppa:redislabs/redis -y -u ; sudo apt install redis -y ; sudo systemctl stop redis\* ; redis-cli --version

    - name: Install phpunit
      env:
        PHPUNIT_VERSION: ${{ matrix.phpunit }}
      run: |
        if [ ! -z "$PHPUNIT_VERSION" ]; then
          composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update -n
          composer install --dev -n
        fi

    - name: Unit tests
      run: ./vendor/bin/phpunit